#!/bin/bash

run()
{
  echo $*
  eval $*
}

CONF=~/git/rc

RC="Eterm ion ion2 config Xdeafults screenrc rpmmacros irbirc colorgccrc
gitconfig vim vimrc cvsrc cvsignore"

for i in $RC; do
  run ln -sf $CONF/$i .$i
done

# run mkdir -p .ssh
# run ln -sf $CONF/ssh/config .ssh

